# Generated by Django 3.2.12 on 2022-08-02 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('url', models.CharField(max_length=500)),
                ('sennior_id', models.IntegerField()),
                ('require_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='grade',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AddField(
            model_name='files',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.member'),
        ),
        migrations.AddField(
            model_name='admission',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.files'),
        ),
        migrations.AddField(
            model_name='admission',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.member'),
        ),
    ]
