# Generated by Django 3.2.12 on 2022-08-02 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20220802_0959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='sennior_id',
            new_name='senior_id',
        ),
    ]
